# Generated by Django 5.2 on 2026-07-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_acceso', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
