# Generated by Django 6.0.5 on 2026-06-05 03:21

import django.db.models.deletion
import learning.models.certificate
import learning.models.classroom
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_seed_roles_and_fix_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('access_code', models.CharField(default=learning.models.classroom.generate_access_code, editable=False, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='learning.course')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms_enrolled', through='learning.ClassroomEnrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeacherResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('word', 'Documento Word'), ('image', 'Imagen'), ('link', 'Enlace externo'), ('other', 'Otro')], default='pdf', max_length=10)),
                ('file_url', models.URLField(help_text='URL del archivo (S3, Cloudinary, Google Drive, etc.)')),
                ('is_public', models.BooleanField(default=True, help_text='True = visible para todos los estudiantes; False = solo para el aula asignada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Curso al que pertenece el recurso (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='learning.course')),
                ('lesson', models.ForeignKey(blank=True, help_text='Lección específica (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='learning.lesson')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Principiante A1'), ('A2', 'Elemental A2'), ('B1', 'Intermedio B1'), ('B2', 'Intermedio Alto B2'), ('C1', 'Avanzado C1'), ('C2', 'Maestría C2')], help_text='Nivel MCER: A1, A2, B1, B2, C1, C2', max_length=2)),
                ('title', models.CharField(help_text='Ej: "Certificado de Inglés A1 — JumpUp UTE"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('certificate_code', models.CharField(default=learning.models.certificate.generate_certificate_code, editable=False, help_text='Código único de verificación del certificado', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('issued', 'Emitido'), ('revoked', 'Revocado')], default='pending', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'level')},
            },
        ),
    ]
