# Generated by Django 5.2 on 2026-06-09 15:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import learning.models.course
import learning.models.user
import learning.utils.media_utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_add_classroom_certificate_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=learning.utils.media_utils.generate_media_path)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('storage_provider', models.CharField(choices=[('local', 'Local'), ('s3', 'Amazon S3'), ('cloudinary', 'Cloudinary')], default='local', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('active', 'Activo'), ('deleted', 'Eliminado')], db_index=True, default='uploaded', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='classroomenrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroomenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=learning.models.course.course_image_path),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exercise',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='language',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='external_url',
            field=models.URLField(blank=True, help_text='Enlace externo independiente del archivo (solo para recursos tipo link)', null=True),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = recurso desactivado sin borrado físico'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=learning.models.user.avatar_upload_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de revisión'), ('issued', 'Emitido'), ('revoked', 'Revocado')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='classroomenrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='classroomenrollment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('A1', 'Principiante A1'), ('A2', 'Elemental A2'), ('B1', 'Intermedio B1'), ('B2', 'Intermedio Alto B2'), ('C1', 'Avanzado C1'), ('C2', 'Maestría C2')], db_index=True, default='A1', max_length=2),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('multiple_choice', 'Opción múltiple'), ('translate', 'Traducir'), ('listen', 'Escuchar'), ('fill_blank', 'Completar espacio'), ('match', 'Emparejar')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Texto'), ('interactive', 'Interactivo'), ('audio', 'Audio')], db_index=True, default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='xp_reward',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teacherresource',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL externa o de intercambio; no requerido si se utiliza media_file', null=True),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['teacher', 'course'], name='learning_cl_teacher_71bc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['access_code'], name='learning_cl_access__502d79_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomenrollment',
            index=models.Index(fields=['student', 'classroom'], name='learning_cl_student_38d137_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['lesson', 'exercise_type'], name='learning_ex_lesson__17f90c_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='learning_mo_course__7897c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(('exercise_type__in', ['multiple_choice', 'translate', 'listen', 'fill_blank', 'match'])), name='valid_exercise_type'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='unique_module_title_per_course'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='learning.mediafile'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_images', to='learning.mediafile'),
        ),
        migrations.AddField(
            model_name='language',
            name='flag_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_flags', to='learning.mediafile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_images', to='learning.mediafile'),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='media_file',
            field=models.ForeignKey(blank=True, help_text='Archivo gestionado por la plataforma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='learning.mediafile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_avatars', to='learning.mediafile'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['level'], name='learning_ce_level_0d9df6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='learning_ce_status_feb4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['language', 'difficulty_level'], name='learning_co_languag_f7e5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='learning_co_slug_b348c5_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['code'], name='learning_la_code_5a0db6_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['slug'], name='learning_la_slug_dd5871_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='learning_le_module__83c7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherresource',
            index=models.Index(fields=['resource_type'], name='learning_te_resourc_0e0978_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherresource',
            index=models.Index(fields=['is_public'], name='learning_te_is_publ_145c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherresource',
            index=models.Index(fields=['is_active'], name='learning_te_is_acti_c64f9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('language', 'title'), name='unique_course_title_per_language'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_language_code'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'title'), name='unique_lesson_title_per_module'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['storage_provider'], name='learning_me_storage_6c02f9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['status'], name='learning_me_status_3315b8_idx'),
        ),
    ]
