# Generated by Django 5.2 on 2026-06-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('audience', models.CharField(choices=[('all', 'Todos los usuarios'), ('students', 'Todos los estudiantes'), ('teachers', 'Todos los profesores'), ('course', 'Estudiantes de un curso específico')], default='all', max_length=20, verbose_name='Audiencia')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='URL del botón (Opcional)')),
                ('action_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto del botón')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Correos enviados')),
                ('is_sent', models.BooleanField(default=False, verbose_name='¿Enviado?')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.course', verbose_name='Curso objetivo (si aplica)')),
            ],
            options={
                'verbose_name': 'Envío masivo',
                'verbose_name_plural': 'Envíos masivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
