# Generated by Django 6.0.6 on 2026-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_backuphistory_announcement_maintenancelog_mediaasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='languages_learning',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='learning.language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages_teaching',
            field=models.ManyToManyField(blank=True, related_name='teacher_profiles', to='learning.language'),
        ),
    ]
