# Generated by Django 6.0.6 on 2026-07-08 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_forumcategory_forumpost_forumreport_forumthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'Sistema'), ('course', 'Curso'), ('payment', 'Pago'), ('certificate', 'Certificado'), ('subscription', 'Suscripción'), ('message', 'Mensaje nuevo'), ('forum', 'Foro'), ('live_session', 'Sesión en vivo')], db_index=True, default='system', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='learning_no_user_id_3e40c1_idx'),
        ),
    ]
