# Generated by Django 5.2 on 2026-07-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_notification_type_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
