# Generated by Django 5.2 on 2026-07-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_userprofile_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_2fa_enabled',
        ),
    ]
