# Generated by Django 6.0.6 on 2026-07-10 22:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_remove_userprofile_is_2fa_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['required_xp', 'name']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='required_value',
            field=models.PositiveIntegerField(default=0, help_text='Valor umbral para el trigger (días de racha, cursos, etc.)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='trigger_type',
            field=models.CharField(choices=[('xp', 'Por XP acumulado'), ('streak', 'Por racha de días'), ('course', 'Por cursos completados'), ('messages', 'Por mensajes enviados'), ('manual', 'Manual / admin')], db_index=True, default='xp', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='learning.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Referencia del gateway de pago', max_length=200),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_languages',
            field=models.PositiveIntegerField(default=1, help_text='Máximo de idiomas que puede aprender el usuario con este plan. 0 = ilimitado.'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
