# Generated by Django 5.2 on 2026-07-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_exercise_audio_url_exercise_options_carrito_catalogo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
