# Generated by Django 6.0.6 on 2026-07-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_remove_payment_order_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
