# Generated by Django 6.0.6 on 2026-07-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_remove_payment_order_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='room_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único para la sala de videollamada', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='content_type',
            field=models.CharField(choices=[('file', 'Archivo'), ('url', 'URL externa'), ('video', 'Video embebido')], default='file', help_text='Tipo de contenido para que Flutter sepa cómo abrirlo.', max_length=10),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='file',
            field=models.FileField(blank=True, help_text='Archivo subido directamente por el profesor.', max_length=500, null=True, upload_to='teacher_resources/%Y/%m/%d/'),
        ),
    ]
