name: Deploy to Production VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploying via SSH to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/idiomas_api_guaman_danny
          
          # 1. Traer los últimos cambios desde GitHub
          git pull origin main
          
          # 2. Activar el entorno e instalar nuevas librerías si existen
          source .venv/bin/activate
          pip install -r requirements.txt
          
          # 3. Correr migraciones de Django
          python manage.py migrate
          
          # 4. Recopilar archivos estáticos (APK, logo, admin CSS)
          python manage.py collectstatic --noinput
          
          # 5. Reiniciar el servicio real de Gunicorn
          sudo systemctl restart gunicorn-shopapi.service